### ISSUE TITLE
OS is not supported. ALAR will stop!

### ISSUE THREAD

**Issue by dambro01** [Azure/repair-script-library#9]
when executed on Centos 7, 8 and RHEL 7.8 I received the following error
Script returned with error:
OS is not supported. ALAR will stop!

NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.8 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.8"

**Comment by malachma** [comment]
Are these custom images or from the Marketplace?
If from the Marketplace could you please let me know of the image names you have used?

Thanks

**Comment by dambro01** [comment]
Marketplace images; I was able to reproduce
Image: RHEL/Skus/7-LVM/Versions/7.8.2020042719

root@repair-rh7lvm:/var/lib/waagent/run-command/download/0/repair-files-20200803231716# cat logs-20200803231716.txt
[Log-Start  08/03/2020 23:17:16]
[Output 08/03/2020 23:17:16]Starting the recovery
[Info 08/03/2020 23:17:16]This could be a SUSE 12 or 15 image
[Info 08/03/2020 23:17:16]File system check start
[Info 08/03/2020 23:17:16]The error state/number is: 0
[Info 08/03/2020 23:17:16]File system check finished
[Info 08/03/2020 23:17:16]File system check start
[Info 08/03/2020 23:17:16]The error state/number is: 0
[Info 08/03/2020 23:17:16]File system check finished
[Info 08/03/2020 23:17:16]File system check start
[Info 08/03/2020 23:17:16]The error state/number is: 0
[Info 08/03/2020 23:17:16]File system check finished
mount: /tmp/assert: special device /dev/disk/azure/scsi1/lun0-part does not exist.
umount: /tmp/assert: not mounted.
[Error 08/03/2020 23:17:16]OS is not supported. ALAR will stop!
[Error 08/03/2020 23:17:16]
[Log-End 08/03/2020 23:17:16]/var/lib/waagent/run-command/download/0/repair-files-20200803231716/logs-20200803231716.txt

NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.8 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.8"

**Comment by malachma** [comment]
Thanks for the info. I have to alter the disk identification logic due to the new layout used on this SKU
The newer SKUs do come with a third partition now.

**Comment by malachma** [comment]
Issue got fixed with commit 4a266017151b093dc334417a70be09b44b3a86bf
Thanks for reporting it dambro01
